# Generated by Django 4.1.7 on 2023-07-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(max_length=30)),
                ('districts', models.CharField(max_length=200)),
            ],
        ),
    ]
